import { Shortcut, ShortcutCategory } from '../types';

export const ALL_SHORTCUTS: Shortcut[] = [
  // All Views
  { id: 1, combo: ['Shift', 'Learn', 'turn Horizontal'], description: 'Adjust brightness', category: ShortcutCategory.ALL_VIEWS },
  { id: 2, combo: ['Shift', 'Select'], description: 'Settings menu', category: ShortcutCategory.ALL_VIEWS },
  { id: 3, combo: ['Back'], description: 'Undo', category: ShortcutCategory.ALL_VIEWS },
  { id: 4, combo: ['Shift', 'Back'], description: 'Redo', category: ShortcutCategory.ALL_VIEWS },
  { id: 5, combo: ['turn Tempo'], description: 'Tempo change', category: ShortcutCategory.ALL_VIEWS },
  { id: 6, combo: ['press & turn Tempo'], description: 'Tempo change +1 BPM', category: ShortcutCategory.ALL_VIEWS },
  { id: 7, combo: ['Shift', 'turn Tempo'], description: 'Swing adjustment', category: ShortcutCategory.ALL_VIEWS },
  { id: 8, combo: ['Shift', 'Tap Tempo'], description: 'Metronome on/off', category: ShortcutCategory.ALL_VIEWS },
  { id: 9, combo: ['Horizontal'], description: 'Check current zoom level', category: ShortcutCategory.ALL_VIEWS },
  { id: 10, combo: ['press & turn Horizontal'], description: 'Change current zoom level', category: ShortcutCategory.ALL_VIEWS },
  { id: 11, combo: ['turn Horizontal'], description: 'Scroll left or right', category: ShortcutCategory.ALL_VIEWS },
  { id: 12, combo: ['turn Vertical'], description: 'Scroll up or down', category: ShortcutCategory.ALL_VIEWS },
  { id: 13, combo: ['Load', 'turn Select', 'then', 'Load'], description: 'Load song (saved tempo)', category: ShortcutCategory.ALL_VIEWS },
  { id: 14, combo: ['Load', 'turn Select', 'then', 'Tempo', 'Load'], description: 'Load song (current tempo)', category: ShortcutCategory.ALL_VIEWS },
  { id: 15, combo: ['Shift', 'Save'], description: 'Delete song', category: ShortcutCategory.ALL_VIEWS },
  { id: 16, combo: ['Shift', 'Load', 'then', 'Load'], description: 'New song', category: ShortcutCategory.ALL_VIEWS },
  { id: 17, combo: ['Load', 'then', 'turn Select'], description: 'Delay load', category: ShortcutCategory.ALL_VIEWS },
  { id: 18, combo: ['Record', 'Play', 'then', 'Record', 'Play'], description: 'Loop resample', category: ShortcutCategory.ALL_VIEWS },
  { id: 19, combo: ['Shift', 'Record'], description: 'Resample', category: ShortcutCategory.ALL_VIEWS },
  { id: 20, combo: ['Horizontal', 'turn Tempo'], description: 'Nudge clock', category: ShortcutCategory.ALL_VIEWS },

  // FX & Parameters
  { id: 21, combo: ['upper Gold'], description: 'LP, HP, EQ option', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [CUTOFF / RES] = on' },
  { id: 22, combo: ['lower Gold'], description: 'LPF slope type', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [CUTOFF / RES] = on' },
  { id: 23, combo: ['upper Gold'], description: 'Ping-Pong on/off', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [DELAY TIME / AMOUNT] = on' },
  { id: 24, combo: ['lower Gold'], description: 'Delay style digital / analog', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [DELAY TIME / AMOUNT] = on' },
  { id: 25, combo: ['upper Gold'], description: 'Compressor sync 8th–32nd', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [SIDECHAIN / REVERB] = on' },
  { id: 26, combo: ['lower Gold'], description: 'Reverb room size preset', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [SIDECHAIN / REVERB] = on' },
  { id: 27, combo: ['upper Gold'], description: 'Effect (song/kit): chorus, flanger, phaser', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [MOD RATE / DEPTH] & Affect Entire = on' },
  { id: 28, combo: ['lower Gold'], description: 'Effect (song/kit): depth, offset, feedback', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [MOD RATE / DEPTH] & Affect Entire = on' },
  { id: 29, combo: ['upper Gold'], description: 'Stutter', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [STUTTER / CUSTOM 1] = on' },
  { id: 30, combo: ['press & turn upper Gold'], description: 'Stutter – ramp speed', category: ShortcutCategory.FX_PARAMETERS, notes: 'Requires [STUTTER / CUSTOM 1] = on' },

  // Song View
  { id: 31, combo: ['Hold Song', 'turn Select'], description: 'Switch song views – default row (change row or grid)', category: ShortcutCategory.SONG_VIEW },
  { id: 32, combo: ['Hold Pad on grid', 'turn upper/lower Gold'], description: 'Clip parameter adjustment', category: ShortcutCategory.SONG_VIEW },
  { id: 33, combo: ['Shift', 'Section'], description: 'Change section assignment / Colour', category: ShortcutCategory.SONG_VIEW },
  { id: 34, combo: ['Hold Pad for row', 'Shift', 'turn Vertical'], description: 'Change pad row colour in row view', category: ShortcutCategory.SONG_VIEW },
  { id: 35, combo: ['Press Section', 'turn Select'], description: 'Section repeats / share status', category: ShortcutCategory.SONG_VIEW },
  { id: 36, combo: ['Hold Pad of row to move', 'turn Vertical'], description: 'Move row', category: ShortcutCategory.SONG_VIEW },
  { id: 37, combo: ['Hold Pad of master clip', 'press Pad of another row'], description: 'Clone clip', category: ShortcutCategory.SONG_VIEW },
  { id: 38, combo: ['Tap Section'], description: 'Solo section', category: ShortcutCategory.SONG_VIEW },
  { id: 39, combo: ['Horizontal', 'press clip’s Launch'], description: 'Solo clip (arm)', category: ShortcutCategory.SONG_VIEW },
  { id: 40, combo: ['Shift', 'press clip’s Launch'], description: 'Solo clip (Immediate)', category: ShortcutCategory.SONG_VIEW },
  { id: 41, combo: ['Press clip’s Mute'], description: 'Un-solo', category: ShortcutCategory.SONG_VIEW },
  { id: 42, combo: ['Shift', 'Mute'], description: 'Instant mute / launch', category: ShortcutCategory.SONG_VIEW },
  { id: 43, combo: ['Hold Pad of clip', 'press Save'], description: 'Delete clip', category: ShortcutCategory.SONG_VIEW },
  { id: 44, combo: ['Hold Pad', 'press Song', 'turn Horizontal', 'release pad'], description: 'Drag clip instance to arranger', category: ShortcutCategory.SONG_VIEW },
  { id: 45, combo: ['Hold Record', 'press Song'], description: 'Record to arranger', category: ShortcutCategory.SONG_VIEW },
  { id: 46, combo: ['upper Gold'], description: 'Master compressor mode', category: ShortcutCategory.SONG_VIEW, notes: 'Requires Affect Entire = ON, [SIDECHAIN] ON' },
  { id: 47, combo: ['Press Audition'], description: 'Grid View – Pad Modes (Green = Set Launch mode / Blue = edit)', category: ShortcutCategory.SONG_VIEW },
  { id: 48, combo: ['Hold Pad of empty clip', 'Select'], description: 'Create audio clip', category: ShortcutCategory.SONG_VIEW },
  { id: 49, combo: ['Hold Learn', 'press Pad of clip'], description: 'Set input source for audio clip', category: ShortcutCategory.SONG_VIEW },
  { id: 50, combo: ['In record mode', 'press Play'], description: 'Loop record (with armed, empty audio clips present)', category: ShortcutCategory.SONG_VIEW },
  { id: 51, combo: ['Press Launch of clip'], description: 'Close loop recording', category: ShortcutCategory.SONG_VIEW },
  { id: 52, combo: ['Horizontal', 'press Launch'], description: 'Close loop + immediate solo', category: ShortcutCategory.SONG_VIEW },
  { id: 53, combo: ['In record mode', 'unmute armed, empty audio clip'], description: 'Loop record during playback', category: ShortcutCategory.SONG_VIEW },
  { id: 54, combo: ['Hold Record', 'press Pad of clip row underneath'], description: 'Overdub', category: ShortcutCategory.SONG_VIEW },
  { id: 55, combo: ['Hold Record', 'press Audition of row underneath'], description: 'Continuous overdub layering', category: ShortcutCategory.SONG_VIEW },
  { id: 56, combo: ['Record loop'], description: '‘Loop pedal’ record (while no other clip is playing and metronome is off)', category: ShortcutCategory.SONG_VIEW },
  { id: 57, combo: ['Tempo', 'press Pad for clip row (Song) or any pad (Clip View)'], description: 'Grab tempo from audio clip', category: ShortcutCategory.SONG_VIEW },
  { id: 58, combo: ['Enter audio clip or hold clip row in song view', 'press switch'], description: 'Select MIDI switch LOOP target', category: ShortcutCategory.SONG_VIEW },
  { id: 59, combo: ['In record mode', 'unmute armed empty clip during playback'], description: 'Auto extending instrument clip record', category: ShortcutCategory.SONG_VIEW },

  // Arranger View
  { id: 60, combo: ['Press Pad'], description: 'Place clip instance', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 61, combo: ['Pad (leftmost start pad of an instance)'], description: 'Delete clip instance', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 62, combo: ['Hold Pad start', 'press Pad end on same row'], description: 'Clip instance length', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 63, combo: ['Hold Pad', 'turn Horizontal'], description: 'Move clip instance horizontally', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 64, combo: ['Hold Pad', 'turn Select'], description: 'Change instance clip', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 65, combo: ['Shift', 'Pad'], description: 'Make clip instance unique (creates a ‘white’ clip)', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 66, combo: ['Hold Pad', 'turn upper/lower Gold for selected parameter'], description: 'Adjust clip instance parameters', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 67, combo: ['Press any clip instance pad other than the first/leftmost'], description: 'Enter clip view for a clip', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 68, combo: ['Hold Pad', 'Song', 'turn Vertical', 'then', 'release pad'], description: 'Drag ‘unique’ clip instance to song view', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 69, combo: ['Hold Audition', 'turn Tempo'], description: 'Quantize or Humanize row (Right = Quantize / Left = Humanize)', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 70, combo: ['Hold Audition', 'turn Vertical'], description: 'Move track', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 71, combo: ['Mute for row'], description: 'Mute / unmute track', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 72, combo: ['Horizontal', 'Mute for instrument'], description: 'Solo track', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 73, combo: ['Hold Audition', 'turn Select or press Synth/Kit/MIDI/CV'], description: 'Change or Add new instrument', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 74, combo: ['Hold Audition', 'Save'], description: 'Delete track row', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 75, combo: ['Audition'], description: 'Audition instrument (Song’s root note or snare drum in kit mode)', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 76, combo: ['Horizontal', 'Back'], description: 'Clear arrangement', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 77, combo: ['Empty lane Audition', 'Select'], description: 'Create new audio track', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 78, combo: ['Learn', 'Audition of audio track'], description: 'Set input source for audio track', category: ShortcutCategory.ARRANGER_VIEW },
  { id: 79, combo: ['Press Play while in Record'], description: 'Record audio from current position (with armed audio present)', category: ShortcutCategory.ARRANGER_VIEW },
  
  // Clip View
  { id: 80, combo: ['Shift', 'turn Vertical'], description: 'Change clip colour', category: ShortcutCategory.CLIP_VIEW },
  { id: 81, combo: ['turn Select'], description: 'Change clip preset, MIDI Ch, CV out', category: ShortcutCategory.CLIP_VIEW },
  { id: 82, combo: ['Shift', 'turn Horizontal'], description: 'Adjust clip length', category: ShortcutCategory.CLIP_VIEW },
  { id: 83, combo: ['Shift', 'Horizontal'], description: 'Duplicate / multiply and append content', category: ShortcutCategory.CLIP_VIEW },
  { id: 84, combo: ['Vertical', 'turn Horizontal'], description: 'Horizontal clip shift / nudge L–R', category: ShortcutCategory.CLIP_VIEW },
  { id: 85, combo: ['Horizontal', 'Play'], description: 'Playback from current screen', category: ShortcutCategory.CLIP_VIEW },
  { id: 86, combo: ['Horizontal', 'Back'], description: 'Clear clip', category: ShortcutCategory.CLIP_VIEW },
  { id: 87, combo: ['Shift', 'Direction Pad'], description: 'Change Clip Direction', category: ShortcutCategory.CLIP_VIEW, notes: 'Direction pad is to the right of OSC SYNC on FM MOD 1' },
  { id: 88, combo: ['Hold Pad start', 'press Pad end on same row'], description: 'Note length', category: ShortcutCategory.CLIP_VIEW },
  { id: 89, combo: ['Press Pad start', 'navigate with Horizontal', 'Horizontal', 'press Pad end'], description: 'Note length – long', category: ShortcutCategory.CLIP_VIEW },
  { id: 90, combo: ['Hold Pad on the grid', 'turn Horizontal'], description: 'Note velocity', category: ShortcutCategory.CLIP_VIEW },
  { id: 91, combo: ['Hold Pad on the grid', 'hold and turn Vertical'], description: 'Note repeat', category: ShortcutCategory.CLIP_VIEW },
  { id: 92, combo: ['Hold Pad of note', 'turn Select (anticlockwise/left)'], description: 'Note play probability %', category: ShortcutCategory.CLIP_VIEW },
  { id: 93, combo: ['Hold All Pads together', 'turn Select (anticlockwise/left)'], description: 'Set dependence on first note', category: ShortcutCategory.CLIP_VIEW },
  { id: 94, combo: ['Hold Pad of note', 'turn Select (clockwise/right)'], description: 'Iteration dependence for a note', category: ShortcutCategory.CLIP_VIEW },
  { id: 95, combo: ['Hold Learn', 'Horizontal'], description: 'Copy notes', category: ShortcutCategory.CLIP_VIEW },
  { id: 96, combo: ['Hold Learn', 'Shift', 'Horizontal'], description: 'Paste notes', category: ShortcutCategory.CLIP_VIEW },
  { id: 97, combo: ['Hold Pad', 'press & turn Horizontal'], description: 'Nudge individual notes horizontally', category: ShortcutCategory.CLIP_VIEW },
  { id: 98, combo: ['Turn upper/lower Gold of selected parameter'], description: 'Automate a parameter (while recording)', category: ShortcutCategory.CLIP_VIEW },
  { id: 99, combo: ['Hold Pad of note start', 'turn upper/lower Gold'], description: 'Per note parameter change', category: ShortcutCategory.CLIP_VIEW },
  { id: 100, combo: ['Shift', 'upper/lower Gold of selected parameter'], description: 'Delete parameter automation', category: ShortcutCategory.CLIP_VIEW },
  { id: 101, combo: ['Hold Learn', 'upper/lower Gold of selected parameter'], description: 'Copy automation', category: ShortcutCategory.CLIP_VIEW },
  { id: 102, combo: ['Hold Learn', 'Shift', 'upper/lower Gold of selected parameter'], description: 'Paste automation', category: ShortcutCategory.CLIP_VIEW },
  { id: 103, combo: ['Audition', 'Load'], description: 'Load sample', category: ShortcutCategory.CLIP_VIEW },
  { id: 104, combo: ['Shift', 'Pad of shortcut as labelled or Select'], description: 'Sound Editor', category: ShortcutCategory.CLIP_VIEW },
  { id: 105, combo: ['Load', 'Synth or Kit or MIDI'], description: 'Preset load interface', category: ShortcutCategory.CLIP_VIEW },
  { id: 106, combo: ['Press Pad of leftmost column at start of waveform'], description: 'Audio clip trim start', category: ShortcutCategory.CLIP_VIEW },
  { id: 107, combo: ['Press Pad of rightmost column at end of waveform'], description: 'Audio clip trim end', category: ShortcutCategory.CLIP_VIEW },
  { id: 108, combo: ['Hold Audition', 'press & turn Vertical'], description: 'Euclidean Seq: Number of events on the row', category: ShortcutCategory.CLIP_VIEW },
  { id: 109, combo: ['Hold Audition', 'turn Horizontal'], description: 'Euclidean Seq: Row length', category: ShortcutCategory.CLIP_VIEW },
  { id: 110, combo: ['Hold Audition', 'press & turn Horizontal'], description: 'Euclidean Seq: Rotate / Shift events or notes', category: ShortcutCategory.CLIP_VIEW },

  // Sound Editor
  { id: 111, combo: ['turn Horizontal'], description: 'Move cursor', category: ShortcutCategory.SOUND_EDITOR },
  { id: 112, combo: ['Hold Learn', 'turn upper/lower Gold'], description: 'Parameter knob assignment', category: ShortcutCategory.SOUND_EDITOR },
  { id: 113, combo: ['Hold Learn', 'turn (MIDI) Control of external device'], description: 'MIDI knob assignment', category: ShortcutCategory.SOUND_EDITOR },
  { id: 114, combo: ['Shift', 'Learn'], description: 'Unassign MIDI control knob', category: ShortcutCategory.SOUND_EDITOR },
  { id: 115, combo: ['Save'], description: 'Save preset', category: ShortcutCategory.SOUND_EDITOR },
  { id: 116, combo: ['Hold Affect Entire while changing parameter'], description: 'Apply a change to entire kit', category: ShortcutCategory.SOUND_EDITOR },

  // Synth, MIDI & CV
  { id: 117, combo: ['Record', 'Audition or grid Pad'], description: 'Synth resample', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 118, combo: ['Shift', 'Synth'], description: 'Load blank synth', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 119, combo: ['Audition', 'Synth'], description: 'Load synth preset to a kit row', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 120, combo: ['Save', 'Synth'], description: 'Save synth preset', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 121, combo: ['Shift', 'Scale'], description: 'Cycle through default scales', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 122, combo: ['Scale', 'Audition row of new note'], description: 'Change root note', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 123, combo: ['Scale'], description: 'Chromatic scale (turn it OFF, LED unlit)', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 124, combo: ['select pad notes', 'then', 'press Scale'], description: 'Create scale (in chromatic mode)', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 125, combo: ['Hold Audition', 'press & turn Select'], description: 'Alter current scale', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 126, combo: ['press & turn Vertical'], description: 'Transpose current clip an octave', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 127, combo: ['Shift', 'press & turn Vertical'], description: 'Transpose current clip a semitone (Chromatic – scale OFF)', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 128, combo: ['Shift', 'press & turn Vertical'], description: 'Transpose ALL clips a semitone (Scale ON)', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 129, combo: ['Hold Pad first column', 'press Pad last column of grid'], description: 'Create full screen ‘drone’ note', category: ShortcutCategory.SYNTH_MIDI_CV },
  { id: 130, combo: ['upper/lower Gold', 'turn Select'], description: 'Assign MIDI CC to parameter knob (MIDI Track)', category: ShortcutCategory.SYNTH_MIDI_CV },

  // Kit Clips
  { id: 131, combo: ['Shift', 'Audition', 'turn Vertical'], description: 'Change colour of specific row', category: ShortcutCategory.KIT_CLIPS },
  { id: 132, combo: ['Save', 'Kit'], description: 'Save kit preset', category: ShortcutCategory.KIT_CLIPS },
  { id: 133, combo: ['Audition for row to edit', 'Random'], description: 'Randomize Kit Row', category: ShortcutCategory.KIT_CLIPS },
  { id: 134, combo: ['Hold Audition for row', 'Mute', 'turn Vertical'], description: 'Move row', category: ShortcutCategory.KIT_CLIPS },
  { id: 135, combo: ['Pad for row to delete', 'Save'], description: 'Delete row', category: ShortcutCategory.KIT_CLIPS },
  { id: 136, combo: ['Kit', 'Shift', 'Save'], description: 'Delete all unused rows', category: ShortcutCategory.KIT_CLIPS },
  { id: 137, combo: ['Shift', 'Kit', 'turn Select', 'Shift', 'Select'], description: 'Slice a sample', category: ShortcutCategory.KIT_CLIPS },
  { id: 138, combo: ['Horizontal'], description: 'Lazy Chop Option (in slicer & number selection)', category: ShortcutCategory.KIT_CLIPS },
  { id: 139, combo: ['Audition', 'Record', 'then', 'Record again'], description: 'Record sample from input (start/end)', category: ShortcutCategory.KIT_CLIPS },
  { id: 140, combo: ['Audition', 'press CV'], description: 'Set kit row output to gate', category: ShortcutCategory.KIT_CLIPS },
  { id: 141, combo: ['Audition', 'turn lower Gold'], description: 'Set kit row CV gate (CV row required)', category: ShortcutCategory.KIT_CLIPS },
  { id: 142, combo: ['Audition', 'press MIDI'], description: 'Set kit row output to MIDI', category: ShortcutCategory.KIT_CLIPS },
  { id: 143, combo: ['Audition', 'turn lower Gold'], description: 'Set kit row MIDI channel (MIDI row required)', category: ShortcutCategory.KIT_CLIPS },
  { id: 144, combo: ['Audition', 'turn upper Gold'], description: 'Set kit row MIDI note (MIDI row required)', category: ShortcutCategory.KIT_CLIPS },

  // Keyboard
  { id: 145, combo: ['Keyboard'], description: 'Select Keyboard view', category: ShortcutCategory.KEYBOARD },
  { id: 146, combo: ['Keyboard', 'turn Select'], description: 'Isomorphic, In-Key or Norns', category: ShortcutCategory.KEYBOARD },
  { id: 147, combo: ['Shift', 'turn Horizontal'], description: 'Note offset', category: ShortcutCategory.KEYBOARD },
  { id: 148, combo: ['Scale', 'Select'], description: 'Change Scale', category: ShortcutCategory.KEYBOARD },
  { id: 149, combo: ['Scale', 'turn Select'], description: 'Change Root Note', category: ShortcutCategory.KEYBOARD },

  // Automation
  { id: 150, combo: ['Press Clip twice'], description: 'Select Automation Mode (flashes blue)', category: ShortcutCategory.AUTOMATION },
  { id: 151, combo: ['Shift', 'Clip or Audition', 'Clip'], description: 'Select Automation Mode', category: ShortcutCategory.AUTOMATION },
  { id: 152, combo: ['Shift', 'Pad or turn Select'], description: 'Select Automation Parameter', category: ShortcutCategory.AUTOMATION },
  { id: 153, combo: ['Affect Entire'], description: 'Select Affected Kit Rows (ON for all, OFF for selected)', category: ShortcutCategory.AUTOMATION },
  { id: 154, combo: ['Horizontal', 'Back'], description: 'Clear Automation', category: ShortcutCategory.AUTOMATION },
  { id: 155, combo: ['Record', 'Play', 'then turn upper/lower Gold'], description: 'Record Automation', category: ShortcutCategory.AUTOMATION },
  { id: 156, combo: ['Learn', 'upper/lower Gold'], description: 'Copy Automation', category: ShortcutCategory.AUTOMATION },
  { id: 157, combo: ['Shift', 'Learn', 'upper/lower Gold'], description: 'Paste Automation', category: ShortcutCategory.AUTOMATION },
  { id: 158, combo: ['Shift', 'upper/lower Gold'], description: 'Delete Automation', category: ShortcutCategory.AUTOMATION },
  { id: 159, combo: ['Shift', 'Interpolation'], description: 'Interpolation On/Off', category: ShortcutCategory.AUTOMATION, notes: 'Interpolation pad is the first column of the grid' },
  { id: 160, combo: ['Press flashing Pad'], description: 'Auto Editor: Check Parameter', category: ShortcutCategory.AUTOMATION },
  { id: 161, combo: ['Press Pad'], description: 'Auto Editor: Set Parameter Column Value', category: ShortcutCategory.AUTOMATION },
  { id: 162, combo: ['Hold Pad', 'turn upper/lower Gold'], description: 'Auto Editor: Change Parameter Column Value', category: ShortcutCategory.AUTOMATION },
  { id: 163, combo: ['Hold Pad (start)', 'Press Pad (end)'], description: 'Auto Editor: Set long automation shape', category: ShortcutCategory.AUTOMATION },
  { id: 164, combo: ['Shift', 'press Waveform shortcut pad'], description: 'Auto Editor: Pad selection mode', category: ShortcutCategory.AUTOMATION, notes: 'Waveform shortcut pad is in the first column' },
  { id: 165, combo: ['turn upper/lower Gold'], description: 'Auto Editor: Pad selection mode edit', category: ShortcutCategory.AUTOMATION },
  { id: 166, combo: ['Shift', 'Horizontal'], description: 'Auto Editor: Duplicate Automation', category: ShortcutCategory.AUTOMATION },
  { id: 167, combo: ['Vertical', 'turn Horizontal'], description: 'Auto Editor: Shift Automation', category: ShortcutCategory.AUTOMATION },
  { id: 168, combo: ['Shift', 'turn Horizontal'], description: 'Auto Editor: Reduce clip length', category: ShortcutCategory.AUTOMATION },
  { id: 169, combo: ['Horizontal'], description: 'Auto Editor: View zoom level', category: ShortcutCategory.AUTOMATION },
  { id: 170, combo: ['press & turn Horizontal'], description: 'Auto Editor: Change zoom level', category: ShortcutCategory.AUTOMATION },
  { id: 171, combo: ['turn Horizontal'], description: 'Auto Editor: Scroll grid', category: ShortcutCategory.AUTOMATION },
];

export const CATEGORIES: ShortcutCategory[] = Object.values(ShortcutCategory);
